#!/usr/bin/env python3
"""Write GitHub Pages stubs for old WordPress URLs still listed in Search Console.

GitHub Pages cannot send HTTP 301. Each real content slug gets a noindex stub
with canonical + meta refresh + JS. Media/attachment junk is left as 404 so
Google can drop it. Re-run this script after editing REDIRECTS.
"""

from __future__ import annotations

import json
from html import escape
from pathlib import Path

SITE_ROOT = Path(__file__).resolve().parents[1]
CANONICAL_HOST = "https://xlhighwaytravel.co.za"
MARKER = "LEGACY-REDIRECT"

# Old WordPress path (trailing slash) -> live path (root-relative, hash ok).
REDIRECTS: list[tuple[str, str]] = [
    ("/contact-form/", "/contact.html"),
    ("/top-destinations/", "/destinations.html"),
    ("/top-destinations/aus3-outback/", "/destinations.html"),
    ("/top-travel-destinations-in-south-africa/", "/destinations.html"),
    ("/ngo-travel/", "/ngo.html"),
    ("/ngo-travel/gilamb/", "/ngo.html"),
    ("/t-cs/", "/terms.html"),
    ("/specials/", "/specials.html"),
    ("/save/", "/specials.html"),
    ("/our-partners/", "/partners.html"),
    ("/our-partners/saa/", "/partners.html"),
    ("/corporate-travel/", "/corporate.html"),
    ("/corporate-travel/travel-support/", "/corporate.html"),
    ("/corporate-travel/peace-of-mind-for-employees-and-managers/", "/corporate.html"),
    ("/competitive-pricing-and-flexibility/", "/corporate.html"),
    ("/xlgo/", "/corporate.html"),
    ("/personnel/sarah-gonggryp/", "/about.html#sarah"),
    ("/sarah/", "/about.html#sarah"),
    ("/trace/", "/about.html#trace"),
    ("/southern-africa/", "/southern-africa.html"),
    ("/southern-africa/guide/", "/southern-africa.html"),
    ("/drakensberg-tours/", "/southern-africa.html#drakensberg"),
    ("/southern-africa/drakensberg-mountain-pass/", "/southern-africa.html#drakensberg"),
    ("/southern-africa/drakensberg-amphitheatre/", "/southern-africa.html#drakensberg"),
    ("/south-africa/drakensberg-san-rock-art/", "/southern-africa.html#drakensberg"),
    ("/southern-africa/victoria-falls/", "/lanseria-harare.html"),
    ("/southern-africa/victoria-falls-2/", "/lanseria-harare.html"),
    ("/south-africa/victoria-falls-2/victoria-falls-3/", "/lanseria-harare.html"),
    ("/southern-africa/kwazulu-natal/", "/southern-africa.html#kzn"),
    ("/south-africa/kwazulu-natal/durban-beach/", "/southern-africa.html#kzn"),
    ("/southern-africa/southern-mozambique/", "/southern-africa.html#mozambique"),
    ("/southern-africa/southern-mozambique/family-beach-holiday-mozambique/", "/southern-africa.html#mozambique"),
    ("/southern-africa/maputo-special-reserve-moz-3/", "/southern-africa.html#mozambique"),
    ("/southern-africa/malawi/", "/southern-africa.html#malawi"),
    ("/lake-malawi/", "/southern-africa.html#malawi"),
    ("/water-sports-lake-malawi/", "/southern-africa.html#malawi"),
    ("/southern-africa/cape-province/", "/southern-africa.html#cape"),
    ("/cape-of-good-hope-1/", "/southern-africa.html#cape"),
    ("/southern-africa/safari-lodges/", "/southern-africa.html#safari"),
    ("/lodges/", "/southern-africa.html#safari"),
    (
        "/let-harvey-world-travel-book-you-a-quiet-bird-watching-retreat-at-one-of-our-top-lodges/",
        "/southern-africa.html#safari",
    ),
    ("/south-africa/guide/", "/southern-africa.html"),
    ("/southern-africa/river-bridge/", "/southern-africa.html"),
    ("/club-med-beach-safari/", "/southern-africa.html"),
    ("/beach-safari/", "/southern-africa.html"),
    ("/rovos-rail-golf-safari-3/", "/southern-africa.html"),
    ("/rovos-rail-golf-safari-itinerary/", "/southern-africa.html"),
    ("/xl-vid1/", "/"),
]


def normalize_from(path: str) -> str:
    if not path.startswith("/"):
        raise ValueError(f"path must start with /: {path}")
    if path != "/" and not path.endswith("/"):
        path += "/"
    return path


def canonical_for(target: str) -> str:
    path = target.split("#", 1)[0]
    if path == "/":
        return f"{CANONICAL_HOST}/"
    return f"{CANONICAL_HOST}{path}"


def stub_html(target: str) -> str:
    dest = escape(target, quote=True)
    canon = escape(canonical_for(target), quote=True)
    return f"""<!DOCTYPE html>
<html lang="en-ZA">
<head>
  <!-- {MARKER}: generated by scripts/write_legacy_redirects.py -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>This page has moved | XL Highway Travel</title>
  <meta name="robots" content="noindex, follow">
  <link rel="canonical" href="{canon}">
  <meta http-equiv="refresh" content="0;url={dest}">
  <meta name="theme-color" content="#8E0D1A">
  <link rel="icon" href="/assets/img/logo.png" type="image/png">
  <link rel="stylesheet" href="/assets/css/styles.css">
  <script>location.replace({json.dumps(target)});</script>
</head>
<body>
  <main class="section" style="min-height:70vh;display:flex;align-items:center">
    <div class="container" style="text-align:center;max-width:560px">
      <a href="/"><img src="/assets/img/logo.png" alt="XL Highway Travel" width="220" height="67" style="margin:0 auto 1.5rem"></a>
      <p class="eyebrow" style="justify-content:center">Page moved</p>
      <h1>This page has a new address</h1>
      <p class="text-muted">You are being sent to the current page on XL Highway Travel.</p>
      <div class="btn-row" style="justify-content:center">
        <a class="btn btn-primary" href="{dest}">Continue</a>
        <a class="btn btn-ghost" href="/">Home</a>
      </div>
    </div>
  </main>
</body>
</html>
"""


def write_js(mapping: dict[str, str]) -> None:
    out = SITE_ROOT / "assets" / "js" / "legacy-redirects.js"
    keys = json.dumps(mapping, indent=2, sort_keys=True)
    out.write_text(
        f"""/* {MARKER}: generated by scripts/write_legacy_redirects.py */
(function () {{
  var MAP = {keys};
  var path = (location.pathname || "/").replace(/\\/index\\.html$/i, "/");
  if (path.length > 1 && path.charAt(path.length - 1) === "/") {{
    path = path.slice(0, -1);
  }}
  var target = MAP[path] || MAP[path + "/"];
  if (target) {{
    location.replace(target);
  }}
}})();
""",
        encoding="utf-8",
    )


def write_stubs(pairs: list[tuple[str, str]]) -> int:
    written = 0
    for raw_from, target in pairs:
        src = normalize_from(raw_from)
        rel = src.strip("/")
        dest = SITE_ROOT / rel / "index.html" if rel else SITE_ROOT / "index.html"
        if dest.resolve() == (SITE_ROOT / "index.html").resolve():
            raise SystemExit(f"Refusing to overwrite the homepage for {src}")
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists():
            existing = dest.read_text(encoding="utf-8")
            if MARKER not in existing:
                raise SystemExit(f"Refusing to overwrite {dest.relative_to(SITE_ROOT)}")
        dest.write_text(stub_html(target), encoding="utf-8")
        written += 1
    return written


def main() -> None:
    seen: dict[str, str] = {}
    for src, target in REDIRECTS:
        src = normalize_from(src)
        if src in seen and seen[src] != target:
            raise SystemExit(f"Duplicate source with different targets: {src}")
        seen[src] = target
    count = write_stubs(list(seen.items()))
    js_map = {}
    for src, target in seen.items():
        js_map[src] = target
        js_map[src.rstrip("/") or "/"] = target
    write_js(js_map)
    print(f"Wrote {count} stubs and assets/js/legacy-redirects.js")


if __name__ == "__main__":
    main()
